name: Main deployment workflow

on: workflow_call

jobs:
  output_variables:
    name: Output variables
    runs-on: windows-latest
    steps:
      - name: output
        run: 
          echo ${{ env }}
          echo ${{ secrets.google_calendar_creds }}
          echo isProduction ${{ env.isProduction }}
          echo path ${{ env.path }}
        
