# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # build api
  api: 
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        #with:
          # Folder location of where vswhere.exe is located if a self-hosted agent
          #vswhere-path: # optional
          # Version of Visual Studio to search; defaults to latest if not specified
          #vs-version: # optional/p:DeployOnBuild=true /p:PublishProfile=FolderProfile
          # Enable searching for pre-release versions of Visual Studio/MSBuild
          #vs-prerelease: # optional
          # The preferred processor architecture of MSBuild. Can be either "x86" or "x64". "x64" is only available from Visual Studio version 17.0 and later.
          #msbuild-architecture: # optional, default is x86
          
      - name: Setup nuget
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        working-directory: ./sckc
        run: nuget restore sckc.sln
        
      - name: Build Web App
        working-directory: ./sckc
        run: msbuild sckc.sln /p:Configuration=Release
        
      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./sckc/sckc.api/data/sckc.data
          # The contents of the file
          contents: ${{ secrets.google_calendar_creds }}
          # The mode of writing to use: `overwrite`, `append`, or `preserve`.
          write-mode: overwrite # optional, default is preserve
        
      # TODO: run unit test
      #
      #

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: published_api
          path: ./sckc/sckc.api

  # build app
  angular-app:
    needs: api
    if: ${{ true }}  # disable for now
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        # with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          # node-version: # optional
      
      - name: Install Dependencies
        working-directory: ./sckc-app
        #if:
        #  steps.cache-nodemodules.outputs.cache-hit != 'true'
        #  # 👆 if cache hits the skip this step.
        run: npm ci
      
      - name: Build
        working-directory: ./sckc-app
        run: npm run build:prod

      - name: Lint
        working-directory: ./sckc-app
        run: npm run lint
        
      - name: Test
        if: ${{ false }}  # disable for now
        working-directory: ./sckc-app
        run: npm run test:prod

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: published_app
          path: ./sckc-app/dist/sckc-app

  # build app
  ftp:
    needs: angular-app
    if: ${{ true }}  # disable for now?
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: ftp-action-app
        if: ${{ true }}  # disable for now?
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@a9644610a0efe63542b1887c9317ce8628f56521
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          # FTP host
          server: ${{ secrets.ftphost}}
          # FTP user
          username: ${{ secrets.ftpuser}}
          # FTP password
          password: ${{ secrets.ftppassword}}
          # Server port to connect to (read your web hosts docs)
          # port: # optional
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          # protocol: # optional
          # Folder to upload from, must end with trailing slash /
          local-dir: /home/runner/work/sckc/sckc/published_app/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: app/
          # Path and name of the state file - this file is used to track which files have been deployed
          state-name: .ftp-deploy-app-sync-state.json # optional
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          # dry-run: # optional
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          # dangerous-clean-slate: # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
          # exclude: # optional
          # How verbose should the information be - minimal, standard, or verbose
          # log-level: # optional
          # strict or loose
          log-level: verbose # optional

      - name: FTP Deployer
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@b4d8a88f104b46a1bcfac8f69b3413986cc0ce28
        uses: sand4rt/ftp-deployer@v1.3
        with:
          # SFTP on
          sftp: false # optional
          # FTP host URL like: ftp.host.com or sftp.host.com
          host: ${{ secrets.ftphost}}
          # FTP port
          #port: # optional, default is 21
          # Ftp username
          username: ${{ secrets.ftpuser}}
          # Ftp password
          password: ${{ secrets.ftppassword}}
          # The remote folder location of your FTP server
          remote_folder: /app/ # optional
          # The local folder location
          local_folder: /home/runner/work/sckc/sckc/published_api/ # optional, default is dist
          # Remove existing files inside FTP remote folder
          cleanup: false # optional
          # includes
          include: '[ "Global.asax", "Web.config", "bin/**" ]' # optional
          # exclude
          #exclude: [] # optional
          # passive
          pasive: false # optional

#       - name: ftp-action-config
#         if: ${{ true }}  # disable for now?
#         # You may pin to the exact commit or the version.
#         # uses: SamKirkland/FTP-Deploy-Action@a9644610a0efe63542b1887c9317ce8628f56521
#         uses: SamKirkland/FTP-Deploy-Action@4.2.0
#         with:
#           # FTP host
#           server: ${{ secrets.ftphost}}
#           # FTP user
#           username: ${{ secrets.ftpuser}}
#           # FTP password
#           password: ${{ secrets.ftppassword}}
#           # Server port to connect to (read your web hosts docs)
#           # port: # optional
#           # protocol to deploy with - ftp, ftps, or ftps-legacy
#           # protocol: # optional
#           # Folder to upload from, must end with trailing slash /
#           local-dir: /home/runner/work/sckc/sckc/published_api/
#           # Path to upload to on the server. Must end with trailing slash /
#           server-dir: app/
#           # Path and name of the state file - this file is used to track which files have been deployed
#           state-name: .ftp-deploy-config-sync-state.json # optional
#           exclude: |
#             - .*
#             - !Global.asax
#             - !Web.config
#           log-level: verbose
      
      - name: ftp-action-bin
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@a9644610a0efe63542b1887c9317ce8628f56521
        if: ${{ false }}  # disable for now
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          # FTP host
          server: ${{ secrets.ftphost}}
          # FTP user
          username: ${{ secrets.ftpuser}}
          # FTP password
          password: ${{ secrets.ftppassword}}
          # Server port to connect to (read your web hosts docs)
          # port: # optional
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          # protocol: # optional
          # Folder to upload from, must end with trailing slash /
          local-dir: /home/runner/work/sckc/sckc/published_api/bin/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: app/bin/
          # Path and name of the state file - this file is used to track which files have been deployed
          state-name: .ftp-deploy-bin-sync-state.json # optional
          
      - name: Alt health check
        # You may pin to the exact commit or the version.
        # uses: indiesdev/curl@60fb289d6e72261f095d7cefd578e659dd1b5182
        uses: indiesdev/curl@v1
        with:
          # The target url
          url: http://www.sheffieldcitykayakclub.co.uk/app/api/gallery # optional
          # timeout (millisec)
          timeout: 30000 # optional, default is 1000
          # show debug message of response
          is_debug: true # optional
            
      - name: URL Health Check
        # You may pin to the exact commit or the version.
        # uses: Jtalk/url-health-check-action@74726480338ca80a0740c2fbc31bb577bb5ad1b0
        if: ${{ true }}  # disable for now?
        uses: Jtalk/url-health-check-action@v2
        with:
          # Target URL(s), split by |
          url: http://www.sheffieldcitykayakclub.co.uk/app/api/gallery
          # Number of unsuccessful attempts to call URL before giving up
          max-attempts: 3 # optional, default is 1
          # Time between attempts (e.g. 3s, 1m)
          retry-delay: 30s # optional, default is 3s
          # Follow redirected location in case request resulted in 3XX status code
          follow-redirect: false # optional, default is false
          # Retry all errors, including 4xx (see man curl on --retry-all-errors).
      
      - name: Delete Artifacts
        if: ${{ true }}  # disable for now?
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          # The name of the artifact to delete; multiple names can be supplied on new lines.
          name: |
            published_api
            published_app
          # Indicates whether the action should fail upon encountering an error.
          failOnError: false # optional, default is true
