name: Production CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy-prod:
        uses: ./.github/workflows/deployment.yml
        with:
            env_type: production
            deployment_path: '' # need to change this back once v1 is released and I move to PR's/staged environment
        secrets:
            google_calendar_creds: ${{ secrets.google_calendar_creds }}
            ftphost: ${{ secrets.ftphost }}
            ftpuser: ${{ secrets.ftpuser }}
            ftppassword: ${{ secrets.ftppassword }}
            sendgrid_apikey: ${{ secrets.sendgrid_apikey }}
            stripe_apikey: ${{ secrets.stripe_apikey_test }}
